Service failure page
co-cddo/domains-register-a-govuk-domain pull request #107
Opened 2024-04-19 12:15 UTC by prakash-gds

This service failure page will be modified once the actual design page is available

Also, added comments on SEND_EMAIL flag

2024-04-19 12:41 UTC, maxf requested changes
This isn't the right approach if you want to be compliant to HTTP (we do). The error page should also return a 500 status code, just like 404 errors. The way to do this in django is to provide a template for the 500 page, which should be automatically shown in case an exception happens in the code.
Having a test for this would also be better.

2024-04-19 12:41 UTC, maxf commented on request_a_govuk_domain/request/views.py
> +            return HttpResponseRedirect(self.failure_url)
I don't think this will return a 500 error page. It just redirects to a normal 200 page.

2024-04-23 09:30 UTC, maxf requested changes
Could you call your template `500.html`. It's an widespread convention and I want to add templates for 404 and 403 errors next.

2024-04-23 16:09 UTC, prakash-gds commented
Closing this as the changes are now under https://github.com/co-cddo/domains-register-a-govuk-domain/pull/117

2024-04-23 16:09 UTC, closed without merging