File Download - cosmatic changes
co-cddo/domains-register-a-govuk-domain pull request #288
Opened 2024-11-13 09:21 UTC by jinnashravan

Application Status - using the label rather than value Datetime to date format.

2024-11-13 09:56 UTC, maxf requested changes
(also, it's "cosmetic")

2024-11-13 09:56 UTC, maxf commented on request_a_govuk_domain/request/admin/model_admins.py
> +        field_value = getattr(obj, field)
infostring please?

2024-11-14 14:08 UTC, dhvander approved these changes

2024-11-15 09:48 UTC, maxf approved these changes

2024-11-15 10:43 UTC, merged