Made the email field in Person model unique.
co-cddo/domains-register-a-govuk-domain pull request #95
Opened 2024-04-08 12:06 UTC by jinnashravan

Deleted the old migration and created a new one.

2024-04-09 08:44 UTC, maxf requested changes

2024-04-09 08:44 UTC, maxf commented on request_a_govuk_domain/request/migrations/0001_initial.py
> +                            ("Fire service", "Fire Service"),
I think we should make it clearer which of the pairs is human-readable and which is for code, as per https://docs.djangoproject.com/en/5.0/ref/models/fields/#choices
So here we should have something like `("FIRE", "Fire Service")` -- or the other way around, or `("JOINT", "Joint Committee")` below.

2024-04-18 16:38 UTC, prakash-gds commented
Closing this as the relevant work was done under https://github.com/co-cddo/domains-register-a-govuk-domain/pull/96 and so no further action on this PR is needed

2024-04-18 16:38 UTC, prakash-gds commented
Closing this as the relevant work was done under https://github.com/co-cddo/domains-register-a-govuk-domain/pull/96 and so no further action on this PR is needed

2024-04-18 16:38 UTC, closed without merging